language: node_js
node_js:
  - "6"
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
script: npm run lint && npm run test
after_success:
- npm run coveralls


deploy:
  provider: npm
  email: "elecwebmaker@gmail.com"
  api_key: 